name: Deploy to Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual execution

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      PI_DEV002: ${{ vars.PI_DEV002 }}
      SSH_USER: ${{ vars.SSH_USER }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: set up ssh keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check if SSH port is open
        run: |
          nc -zv $PI_DEV002 22 || echo "SSH port is not reachable"

      - name: Debug SSH Connection
        run: |
          ssh -vvv -o StrictHostKeyChecking=no $SSH_USER@$PI_DEV002 "hostname"

      
      - name: Deploy to Dev
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$PI_DEV002 "hostname"

