name: Deploy to Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual execution

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      PI_DEV002: ${{ vars.PI_DEV002 }}
      SSH_USER: ${{ vars.SSH_USER }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote server to known_hosts
        run: |
          for i in {1..5}; do
            ssh-keyscan -t rsa,ed25519 -H ${{ env.PI_DEV002 }} >> ~/.ssh/known_hosts && break
            echo "Retrying ssh-keyscan ($i/5)..."
            sleep 5
          done


      - name: Deploy to server
        run: |
          timeout 30s ssh ${{ env.SSH_USER }}@${{ env.PI_DEV002 }} << 'EOF'
            whoami
          EOF || echo "SSH command timed out"