name: Deploy to Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual execution

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa,ed25519 -H ${{ env.PI_DEV002 }} 2>/dev/null >> ~/.ssh/known_hosts || echo "SSH Keyscan Failed"

      - name: Debug SSH Key
        run: |
          echo "Checking SSH Key and Known Hosts..."
          ls -lah ~/.ssh
          cat ~/.ssh/id_rsa || echo "No private key found"
          cat ~/.ssh/known_hosts || echo "No known hosts found"

      - name: Test SSH Connection
        run: |
          echo "Testing SSH Connection..."
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.PI_DEV002 }} "echo SSH Connection Successful"

      - name: Deploy to Dev
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.PI_DEV002 }} << 'EOF'
            cd ~/homelab-pgadmin
            git pull
            docker-compose --env-file .env.dev up -d
          EOF
