name: Manual Production Deploy

on:
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ vars.PI_PROD002 }} >> ~/.ssh/known_hosts

      - name: Create remote directory
        run: ssh -i ~/.ssh/deploy_key ${{ vars.SSH_USER }}@${{ vars.PI_PROD002 }} 'mkdir -p ~/homelab-pgadmin'

      - name: Copy Docker Compose file to destination
        run: |
          scp -i ~/.ssh/deploy_key ./docker-compose.yaml ${{ vars.SSH_USER }}@${{ vars.PI_PROD002 }}:~/homelab-pgadmin/docker-compose.yaml
          scp -i ~/.ssh/deploy_key ./.env.prod ${{ vars.SSH_USER }}@${{ vars.PI_PROD002 }}:~/homelab-pgadmin/.env.prod

      - name: SSH and deploy with Docker Compose
        run: |
          ssh -i ~/.ssh/deploy_key ${{ vars.SSH_USER }}@${{ vars.PI_PROD002 }} << 'EOF'
            cd ~/homelab-pgadmin
            sudo docker compose --env-file .env.prod up -d
          EOF

      - name: Cleanup SSH key
        run: rm -f ~/.ssh/deploy_key
