name: Deploy Docker Compose via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H 10.7.0.79 >> ~/.ssh/known_hosts

      - name: Create homelab-pgadmin directory
        run: ssh -i ~/.ssh/deploy_key nick@10.7.0.79 'mkdir -p ~/homelab-pgadmin'

      - name: Copy Docker Compose file to destination
        run: |
          scp -i ~/.ssh/deploy_key ./docker-compose.yaml nick@10.7.0.79:~/homelab-pgadmin/docker-compose.yaml

      - name: SSH and deploy with Docker Compose
        run: |
          ssh -i ~/.ssh/deploy_key nick@10.7.0.79 << 'EOF'
            cd ~/homelab-pgadmin
            docker-compose -env-file .env.dev up -d
          EOF

      - name: Cleanup SSH key
        run: rm -f ~/.ssh/deploy_key
