name: Deploy to Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual execution

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      PI_DEV002: ${{ vars.PI_DEV002 }}
      SSH_USER: ${{ vars.SSH_USER }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: set up ssh keys to /root/.ssh
        run: |
          sudo mkdir -p /root/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /root/.ssh/id_rsa
          sudo chmod 600 /root/.ssh/id_rsa
          sudo ssh-keyscan -t rsa ${{ env.PI_DEV002 }} >> /root/.ssh/known_hosts
          sudo chmod 644 /root/.ssh/known_hosts

      - name: Deploy to Dev
        run: |
          ssh -i /root/.ssh/id_rsa ${{ env.SSH_USER }}@${{ env.PI_DEV002 }} 'hostname'