name: Deploy Docker Compose via SSH

on:
  push:
    branches:
      - main

env:
  PI_DEV002: ${{ vars.PI_DEV002 }}
  PI_PROD002: ${{ vars.PI_PROD002 }}
  SSH_USER: ${{ vars.SSH_USER }}

jobs:
  deploy-dev:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ env.PI_DEV002 }} >> ~/.ssh/known_hosts

      - name: Create homelab-pgadmin directory
        run: ssh -i ~/.ssh/deploy_key ${{ env.SSH_USER }}@${{ env.PI_DEV002 }} 'mkdir -p ~/homelab-pgadmin'

      - name: Copy Docker Compose file to destination
        run: |
          scp -i ~/.ssh/deploy_key ./docker-compose.yaml ${{ env.SSH_USER }}@${{ env.PI_DEV002 }}:~/homelab-pgadmin/docker-compose.yaml
          scp -i ~/.ssh/deploy_key ./.env.dev ${{ env.SSH_USER }}@${{ env.PI_DEV002 }}:~/homelab-pgadmin/.env.dev

      - name: SSH and deploy with Docker Compose
        run: |
          ssh -i ~/.ssh/deploy_key ${{ env.SSH_USER }}@${{ env.PI_DEV002 }} << 'EOF'
            cd ~/homelab-pgadmin
            sudo docker compose --env-file .env.dev up -d
          EOF

      - name: Cleanup SSH key
        run: rm -f ~/.ssh/deploy_key

  deploy-prod:
    runs-on: [self-hosted]
    needs: deploy-dev
    environment:
      name: production
      url: http://${{ vars.PI_PROD002 }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ env.PI_PROD002 }} >> ~/.ssh/known_hosts

      - name: Create homelab-pgadmin directory
        run: ssh -i ~/.ssh/deploy_key ${{ env.SSH_USER }}@${{ env.PI_PROD002 }} 'mkdir -p ~/homelab-pgadmin'

      - name: Copy Docker Compose file to destination
        run: |
          scp -i ~/.ssh/deploy_key ./docker-compose.yaml ${{ env.SSH_USER }}@${{ env.PI_PROD002 }}:~/homelab-pgadmin/docker-compose.yaml
          scp -i ~/.ssh/deploy_key ./.env.prod ${{ env.SSH_USER }}@${{ env.PI_PROD002 }}:~/homelab-pgadmin/.env.prod

      - name: SSH and deploy with Docker Compose
        run: |
          ssh -i ~/.ssh/deploy_key ${{ env.SSH_USER }}@${{ env.PI_PROD002 }} << 'EOF'
            cd ~/homelab-pgadmin
            sudo docker compose --env-file .env.prod up -d
          EOF

      - name: Cleanup SSH key
        run: rm -f ~/.ssh/deploy_key
