name: Deploy to Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual execution

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      PI_DEV002: ${{ vars.PI_DEV002 }}
      SSH_USER: ${{ vars.SSH_USER }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private.key
          chmod 400 private.key

      - name: Start SSH Agent and Add Key
        run: |
          eval `ssh-agent -s`
          ssh-add private.key

      - name: Add remote server to known_hosts
        run: |
          mkdir -p ~/.ssh  # Ensure the .ssh directory exists
          touch ~/.ssh/known_hosts  # Ensure known_hosts file exists
          chmod 600 ~/.ssh/known_hosts  # Set proper permissions
          for i in {1..5}; do
            ssh-keyscan -t rsa,ed25519 -H ${{ env.PI_DEV002 }} >> ~/.ssh/known_hosts && break
            echo "Retrying ssh-keyscan ($i/5)..."
            sleep 5
          done


      - name: Deploy to server
        run: |
          timeout 30s ssh -o StrictHostKeyChecking=no -T ${{ env.SSH_USER }}@${{ env.PI_DEV002 }} << 'EOF'
          whoami
          EOF
        shell: bash



      - name: Cleanup SSH Key
        if: always()
        run: rm -f private.key
