name: Deploy to Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual execution

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      PI_DEV002: ${{ vars.PI_DEV002 }}
      PROD_HOST: ${{ vars.PROD_HOST }}
      SSH_USER: ${{ vars.SSH_USER }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug SSH Variables
        run: |
          echo "SSH_USER: '${{ env.SSH_USER }}'"
          echo "PI_DEV002: '${{ env.PI_DEV002 }}'"

      - name: Deploy using appleboy/ssh-action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.PI_DEV002 }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "SSH Connection Successful!"
            cd ~/homelab-pgadmin
            git pull
            docker-compose --env-file .env.dev up -d
          debug: true
